apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: t5gcv0y66-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-0030200269.qh73.p3.openshiftapps.com/rhtap/rhtap-qe:d9eeff667ef3f1b91e301d6eb227dd2df5e0a78b@sha256:07d14aa22c9237a859e4b7c174601c1cde5a0f0a2ed322c80e0bf865d810e7c6
          name: container-image
